apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 5672 
    targetPort: 5672
    protocol: TCP
  selector:
    name: rabbitmq

